{
    'name'              : 'Material Request',
    'version'           : '14.0.1',
    'summary'           : """This module allow your employees/users to create Material Request.""",
    'description'       : """Material Request""",
    'author'            : 'Dani R / Tian',
    'website'           : 'https://www.bemosoft.com',
    'support'           : 'daniramdani@bemosoft.com',
    'images'            : ['static/description/img1.jpeg'],
    'category'          : 'Warehouse',
    'depends'           : [
                            'stock',
                            'hr',
                            'mrp',
                            'bmo_mrp',
                            'bmo_inventory',
                            'bmo_mrp_packing',
                         ],
    'data'              : [
                            'security/security.xml',
                            'security/ir.model.access.csv',
                            'data/purchase_requisition_sequence.xml',
                            'data/employee_purchase_approval_template.xml',
                            'data/confirm_template_material_purchase.xml',
                            'report/paperformat.xml',
                            'report/report_layout.xml',
                            'report/report_material_request.xml',
                            'report/report_mr.xml',
                            'report/report.xml',
                            'views/default_location_view.xml',
                            'views/purchase_requisition_view.xml',
                            'views/res_config_view.xml',
                            'views/config_special_product_view.xml',
                            'views/hr_employee_view.xml',
                            'views/hr_department_view.xml',
                            'views/stock_picking_view.xml',
                            'views/menu_view.xml',
                         ],
    'installable': True,
    'application': False,
}
